# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, verbose_name='Categoría')),
                ('description', models.CharField(blank=True, max_length=140, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=40, verbose_name='Clase')),
                ('description', models.CharField(blank=True, max_length=140, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=60, verbose_name='Nombre Comercial')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=40, verbose_name='Telefono')),
                ('alt_phone', models.CharField(max_length=40, verbose_name='Telefono Alternativo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=40, verbose_name='Telefono')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_name', models.CharField(max_length=40, verbose_name='Trabajo')),
                ('time_required', models.IntegerField(verbose_name='Tiempo')),
                ('description', models.CharField(blank=True, max_length=140, verbose_name='Descripción')),
                ('belongs_to_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Class', verbose_name='Clase')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, verbose_name='Modelo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Brand', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=40, verbose_name='Repuesto')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('cost', models.FloatField(verbose_name='Costo')),
                ('provider', models.CharField(blank=True, max_length=140, verbose_name='Proveedores')),
                ('description', models.CharField(blank=True, max_length=140, verbose_name='Descripción')),
                ('belongs_to_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Class', verbose_name='Clase')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(max_length=20, verbose_name='Patente')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('year', models.CharField(max_length=20, verbose_name='Año')),
                ('transmission', models.CharField(max_length=20, verbose_name='Transmisión')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client', verbose_name='Cliente')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Model', verbose_name='Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=140, verbose_name='Notas')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Vehicle', verbose_name='Vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='labor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.Labor', verbose_name='Trabajo'),
        ),
        migrations.AddField(
            model_name='detail',
            name='part',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.Part', verbose_name='Repuesto'),
        ),
        migrations.AddField(
            model_name='detail',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.WorkOrder', verbose_name='Orden de Trabajo'),
        ),
    ]
