# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=60, verbose_name='Nombre Comercial')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=40, verbose_name='Telefono')),
                ('alt_phone', models.CharField(max_length=40, verbose_name='Telefono Alternativo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
        ),
    ]
