# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, verbose_name='Modelo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Brand', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(max_length=20, verbose_name='Patente')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('year', models.CharField(max_length=20, verbose_name='Año')),
                ('transmission', models.CharField(max_length=20, verbose_name='Transmisión')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client', verbose_name='Cliente')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Model', verbose_name='Modelo')),
            ],
        ),
    ]
