# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.Category', verbose_name='Categoría'),
        ),
    ]
