# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170711_0633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.AddField(
            model_name='workorder',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
