# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170707_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='work_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.WorkOrder', verbose_name='Orden de Servicio'),
        ),
        migrations.AddField(
            model_name='part',
            name='work_order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.WorkOrder', verbose_name='Orden de Servicio'),
        ),
    ]
