# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170711_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='total',
        ),
        migrations.AddField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
