# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170711_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='note',
            field=models.CharField(blank=True, max_length=140, verbose_name='Observaciones'),
        ),
    ]
