# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_vehicle_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='transmission',
        ),
        migrations.AddField(
            model_name='client',
            name='cuit',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(default=1, max_length=20, verbose_name='Motor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nro. Motor'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='kilometers',
            field=models.IntegerField(default=0, verbose_name='Kilometraje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nro. Serie'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='diagnostic',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='fuel_level',
            field=models.CharField(choices=[('EMPTY', 'Vacío'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('FULL', 'Lleno')], default='FULL', max_length=10, verbose_name='Nivel combustible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='initial_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Iniciales'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('PRE', 'Presupuesto'), ('REV', 'Revisión Inicial'), ('ING', 'Esperando Ingreso'), ('ABI', 'Abierta'), ('INI', 'Iniciada'), ('REP', 'Esperando repuestos'), ('RET', 'Esperando Retiro'), ('COM', 'Completa'), ('CER', 'Cerrada'), ('CAN', 'Cancelada')], max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('PRE', 'Presupuesto'), ('REV', 'Revisión Inicial'), ('ING', 'Esperando Ingreso'), ('ABI', 'Abierta'), ('INI', 'Iniciada'), ('REP', 'Esperando repuestos'), ('RET', 'Esperando Retiro'), ('COM', 'Completa'), ('CER', 'Cerrada'), ('CAN', 'Cancelada')], max_length=3, verbose_name='Estado'),
        ),
    ]
