# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170713_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='work',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.Category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.Category', verbose_name='Categoría'),
        ),
    ]
