# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180112_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
