# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180112_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro. Factura'),
        ),
    ]
