# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_workorder_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='display_name',
            field=models.CharField(default='default', max_length=20, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
