# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_employee_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkorderParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='part',
            name='price',
        ),
        migrations.RemoveField(
            model_name='part',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='part',
            name='work_order',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='note',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='workorderparts',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Part', verbose_name='Repuesto'),
        ),
        migrations.AddField(
            model_name='workorderparts',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WorkOrder', verbose_name='Orden de Servicio'),
        ),
    ]
