# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180114_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='parts',
            field=models.ManyToManyField(through='main.WorkorderParts', to='main.Part'),
        ),
    ]
