# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_workorder_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkorderWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_required', models.IntegerField(default=1, verbose_name='Tiempo')),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='time_required',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_order',
        ),
        migrations.AddField(
            model_name='workorderworks',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Work', verbose_name='Trabajo'),
        ),
        migrations.AddField(
            model_name='workorderworks',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WorkOrder', verbose_name='Orden de Servicio'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='works',
            field=models.ManyToManyField(through='main.WorkorderWorks', to='main.Work'),
        ),
    ]
