# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180114_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nombre Comercial'),
        ),
    ]
