# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180116_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Nro. Cliente'),
        ),
    ]
