# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180116_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='fuel_level',
            field=models.CharField(blank=True, choices=[('EMPTY', 'Vacío'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('FULL', 'Lleno')], max_length=10, verbose_name='Nivel combustible'),
        ),
    ]
