# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180116_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderparts',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='workorderworks',
            name='time_required',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tiempo'),
        ),
    ]
