# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180116_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='work',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Código'),
        ),
    ]
