# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180117_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='employee',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Employee', verbose_name='Empleado'),
        ),
    ]
