# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180117_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kilometers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraje'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Año'),
        ),
    ]
