# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-08 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_workorder_kilometers'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nombre Completo'),
        ),
    ]
