# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_client_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRE', 'Presupuesto'), ('REV', 'Revisión Inicial'), ('ING', 'Esperando Ingreso'), ('ABI', 'Abierta'), ('INI', 'Iniciada'), ('REP', 'Esperando repuestos'), ('PAU', 'Pausada'), ('RET', 'Esperando Retiro'), ('COM', 'Completa'), ('CER', 'Cerrada'), ('CAN', 'Cancelada')], max_length=3, verbose_name='Estado')),
                ('date', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=140, verbose_name='Observaciones')),
            ],
        ),
    ]
