# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_movement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkorderMovements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=140, verbose_name='Observaciones')),
            ],
        ),
        migrations.RemoveField(
            model_name='movement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='note',
        ),
        migrations.AddField(
            model_name='workordermovements',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movement', verbose_name='Movimiento'),
        ),
        migrations.AddField(
            model_name='workordermovements',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WorkOrder', verbose_name='Orden de Servicio'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='movements',
            field=models.ManyToManyField(through='main.WorkorderMovements', to='main.Movement'),
        ),
    ]
