# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180301_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordermovements',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='workordermovements',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='movements',
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.DeleteModel(
            name='WorkorderMovements',
        ),
    ]
