# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180301_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRE', 'Presupuesto'), ('REV', 'Revisión Inicial'), ('ING', 'Esperando Ingreso'), ('ABI', 'Abierta'), ('INI', 'Iniciada'), ('REP', 'Esperando repuestos'), ('PAU', 'Pausada'), ('RET', 'Esperando Retiro'), ('COM', 'Completa'), ('CER', 'Cerrada'), ('CAN', 'Cancelada')], max_length=3, verbose_name='Estado')),
                ('date', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=140, verbose_name='Observaciones')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WorkOrder', verbose_name='Orden de Servicio')),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
