# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20180301_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('En Progreso', 'En Progreso'), ('Esperando repuestos', 'Esperando repuestos'), ('Pausada', 'Pausada'), ('Completa', 'Completa'), ('Cerrada', 'Cerrada'), ('Cancelada', 'Cancelada'), ('Presupuesto', 'Presupuesto')], max_length=64, verbose_name='Estado'),
        ),
    ]
