# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20180301_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
