# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 00:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20180301_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 2, 0, 21, 23, 172925, tzinfo=utc), verbose_name='Hora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='status',
            field=models.CharField(blank=True, choices=[('Abierta', 'Abierta'), ('En Progreso', 'En Progreso'), ('Esperando repuestos', 'Esperando repuestos'), ('Pausada', 'Pausada'), ('Completa', 'Completa'), ('Cerrada', 'Cerrada'), ('Cancelada', 'Cancelada'), ('Presupuesto', 'Presupuesto')], max_length=64, verbose_name='Estado'),
        ),
    ]
