# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20180301_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateField(blank=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='time',
            field=models.TimeField(blank=True, verbose_name='Hora'),
        ),
    ]
