# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20180301_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='date_in',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='date_out',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='status',
        ),
        migrations.AddField(
            model_name='movement',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Employee', verbose_name='Empleado'),
        ),
    ]
