# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20180302_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='movement',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('En Progreso', 'En Progreso'), ('Esperando repuestos', 'Esperando repuestos'), ('Pausada', 'Pausada'), ('Completa', 'Completa'), ('Cerrada', 'Cerrada'), ('Cancelada', 'Cancelada'), ('Presupuesto', 'Presupuesto')], default='Abierta', max_length=64, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='note',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='total_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sobreescribir Total'),
        ),
    ]
