# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20180314_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
