# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-27 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20180326_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 16, 9, 4, 28412), verbose_name='Inicio'),
        ),
    ]
