# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-27 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20210127_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Inicio'),
        ),
    ]
