# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-27 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20210127_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='firma_texto_entrada',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Texto de firma al ingresar vehículo'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='firma_texto_salida',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Texto de firma al salir vehículo'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='firma_entrada',
            field=jsignature.fields.JSignatureField(blank=True, null=True, verbose_name='Firma ingreso a taller'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='firma_salida',
            field=jsignature.fields.JSignatureField(blank=True, null=True, verbose_name='Firma salida de taller'),
        ),
    ]
