# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-28 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20210127_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='full_name',
        ),
        migrations.AddField(
            model_name='workorder',
            name='client_alt_phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefono Alternativo'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='client_business_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre Comercial'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='client_cuit',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='client_phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vehicle_engine',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Motor'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vehicle_engine_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nro. Motor'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vehicle_licence_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Patente'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vehicle_vin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nro. Serie'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vehicle_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='firma_texto_entrada',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Texto de Firma ingreso a taller'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='firma_texto_salida',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Texto de Firma salida de taller'),
        ),
    ]
