# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-28 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20210127_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='client_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nro. Cliente'),
        ),
    ]
