# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-28 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_workorder_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
