# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-28 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20210127_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
