# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-28 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20210128_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderworks',
            name='work_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sobreescribir Total'),
        ),
    ]
