# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-28 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20210128_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderworks',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Precio de la hora de Trabajo'),
        ),
        migrations.AlterField(
            model_name='workorderworks',
            name='work_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio total del Trabajo'),
        ),
    ]
