# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-28 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20210128_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderworks',
            name='labor_rate',
            field=models.IntegerField(default=0, verbose_name='Precio de la hora de Trabajo'),
        ),
    ]
